USE HOTEL
GO

INSERT INTO DOCUMENTTYPE (Nombre, Activo)
SELECT 'C.C.',1 UNION ALL
SELECT 'PAS',1 

INSERT INTO GENDER (Nombre, Actibvo)
SELECT 'M', 1 UNION ALL
SELECT 'F', 1 

INSERT INTO THIRDTYPE(Nombre, Activo)
SELECT 'Agente', 1 UNION ALL
SELECT 'Cliente', 1

INSERT INTO ROL(Nombre, Activo)
SELECT 'Interno', 1 UNION ALL
SELECT 'Externo', 1

