CREATE DATABASE HOTEL
GO

USE HOTEL
GO

CREATE TABLE THIRDTYPE 
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Nombre NVARCHAR(250) NOT NULL,
	Activo BIT NOT NULL
)

CREATE TABLE GENDER
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre NVARCHAR(250) NOT NULL,
	Actibvo BIT NOT NULL
)

CREATE TABLE DOCUMENTTYPE
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nombre NVARCHAR(250) NOT NULL,
	Activo BIT NOT NULL
)

CREATE TABLE THIRD
(
	Id BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PrimerNombre NVARCHAR(250) NOT NULL,
	SegundoNombre NVARCHAR(250) NULL,
	PrimerApellido NVARCHAR(250) NOT NULL,
	SegundoApellido NVARCHAR(250) NULL,
	FechNacimiento DATETIME NULL,
	GeneroId INT NOT NULL,
	TipoDocumento INT NOT NULL,
	NumeroDocumento INT NULL,
	Email NVARCHAR(250) NOT NULL,
	TelefonoContato NVARCHAR(12) NOT NULL,
	ThirdTypeId INT NOT NULL
	CONSTRAINT FK_Genero FOREIGN KEY (GeneroId)
	REFERENCES GENDER(Id),
	CONSTRAINT Fk_DOCUMENTTYPE FOREIGN KEY (TipoDocumento)
	REFERENCES DOCUMENTTYPE(Id),
	CONSTRAINT Fk_ThirdType FOREIGN KEY (ThirdTypeId)
	REFERENCES THIRDTYPE(Id)
)

CREATE TABLE ROL
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre NVARCHAR(250) NOT NULL,
	Activo BIT NOT NULL
)

CREATE TABLE USERS
(
	Id BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	USR NVARCHAR(100) NOT NULL,
	PWD NVARCHAR(MAX) NOT NULL,
	Activo BIT NOT NULL,
	RolId INT NOT NULL,
	ThirdId BIGINT NOT NULL,
	CONSTRAINT Fk_Rol FOREIGN KEY(RolId)
	REFERENCES ROL(Id),
	CONSTRAINT Fk_Third FOREIGN KEY (ThirdId)
	REFERENCES THIRD(Id)
)

CREATE TABLE HOTEL
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre NVARCHAR(250) NOT NULL,
	Direccion NVARCHAR(500) NOT NULL,
	Descripcion NVARCHAR(MAX) NOT NULL,
	Ativo BIT NOT NULL
)

CREATE TABLE HABITACIONES
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Habitaion NVARCHAR(200) NOT NULL,
	Ubicacion NVARCHAR(200) NOT NULL,
	HabitacionTipo NVARCHAR(200) NOT NULL
)

CREATE TABLE DETALLEHABITACION
(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CostoBase MONEY NOT NULL,
	Impuestos MONEY NOT NULL,
	HabitacionId INT NOT NULL,
	HotelId INT NOT NULL,
	Activa BIT NOT NULL,
	CONSTRAINT Fk_habitaciondet FOREIGN KEY (HabitacionId)
	REFERENCES HABITACIONES(Id),
	CONSTRAINT Fk_habitacionhotid FOREIGN KEY (HotelId)
	REFERENCES HOTEL(Id)
)

CREATE TABLE RESERVA
(
	Id BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	HabitacionId INT NOT NULL,
	ThirdId BIGINT NOT NULL,
	FECHAI DATETIME NOT NULL,
	FECHAF DATETIME NOT NULL,
	CANTIDADPERSONAS INT NOT NULL,
	CIUDAD NVARCHAR(200)NOT NULL,
	CONSTRAINT Fk_habitacionreserva FOREIGN KEY(HabitacionId)
	REFERENCES HABITACIONES(Id),
	CONSTRAINT Fk_ThirdReserva FOREIGN KEY(ThirdId)
	REFERENCES THIRD(Id)
)

CREATE TABLE DETALLEPERSONASRESERVA
(	
	Id BIGINT PRIMARY KEY NOT NULL IDENTITY(1,1),
	ThirdId BIGINT NOT NULL,
	ReservaId BIGINT NOT NULL,
	CONSTRAINT Fk_ThirdReservaDealle FOREIGN KEY(ThirdId)
	REFERENCES THIRD(Id),
	CONSTRAINT Fk_Reserva FOREIGN KEY(ReservaId)
	REFERENCES RESERVA(Id)
)

